# Site settings
title: Biohack Academy Syllabus
email: info@garagemfablab.com
description: > # this means to ignore newlines until "baseurl:"
  Waag Society's first Biohack Academy is an intense 10 week bioreactor hacking course held in the Amsterdam Fablab and Open Wetlab.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://garagemfablab.github.io" # the base hostname & protocol for your site
twitter_username: GaragemFabLab
github_username:  garagemfablab

# Build settings
markdown: kramdown
